package com.example.medipoint.Viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.medipoint.Data.Appointment
import com.example.medipoint.Data.FirestoreAppointmentDao
import com.example.medipoint.Repository.AppointmentRepository
import com.google.firebase.auth.FirebaseAuth
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow // Added for consistency
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch

class BookingViewModel(
    private val repository: AppointmentRepository = AppointmentRepository(FirestoreAppointmentDao())
) : ViewModel() {

    private val _appointments = MutableStateFlow<List<Appointment>>(emptyList())
    val appointments: StateFlow<List<Appointment>> = _appointments

    private val _saveStatus = MutableStateFlow<Result<Appointment>?>(null)
    val saveStatus: StateFlow<Result<Appointment>?> = _saveStatus

    /**
     * Start listening for realtime updates to this user's appointments.
     */
    fun startAppointmentsListener() {
        val userId = FirebaseAuth.getInstance().currentUser?.uid ?: return
        repository.listenAppointments(
            userId = userId,
            onDataChange = { list -> _appointments.value = list },
            onError = { _appointments.value = emptyList() }
        )
    }

    /**
     * Save a new appointment.
     */
    fun saveAppointment(
        doctorName: String,
        appointmentType: String,
        date: String,
        time: String,
        notes: String
    ) {
        val userId = FirebaseAuth.getInstance().currentUser?.uid
        if (userId == null) {
            // Potentially update _saveStatus with an error if user is not logged in
            // _saveStatus.value = Result.failure(Exception("User not logged in"))
            return
        }

        val newAppointment = Appointment(
            // id will be generated by Firestore, so it's not set here initially
            doctorName = doctorName,
            appointmentType = appointmentType,
            date = date,
            time = time,
            status = "Scheduled",
            notes = notes,
            userId = userId
            // Populate other fields from your expanded Appointment class as needed
        )

        viewModelScope.launch {
            val result: Result<Appointment> = repository.addAppointment(newAppointment)
            _saveStatus.value = result // This will now work
        }
    }

}

